### ISSUE TITLE
写代码了，阵浊秀

### ISSUE THREAD

**Issue by zg19990220** [cxz9805/mall#8]

**Comment by zg19990220** [comment]
> _No description provided._

**Comment by cxz9805** [comment]
代码已经不属于我了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cxz9805/mall"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 上午10:57
收件人:&nbsp;"cxz9805/mall"<mall@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [cxz9805/mall] 写代码了，阵浊秀 (#8)





 
Closed #8.
